package uti

fun Const.ApiUrl.FooterLinks() = this.url + "footer_links/"
fun Const.ApiUrl.Sponsors() = this.url + "sponsors/"
fun Const.ApiUrl.Profiles() = this.url + "profiles/"
fun Const.ApiUrl.Projects() = this.url + "projects/"
fun Const.ApiUrl.Section() = this.url + "section/"
fun Const.ApiUrl.Hardwares() = this.url + "hardwares/"
fun Const.ApiUrl.HardwareRentals() = this.url + "hardware_rentals/"
fun Const.ApiUrl.Gallery() = this.url + "gallery/"
fun Const.ApiUrl.Files() = this.url + "files/"
fun Const.ApiUrl.Tags() = this.url + "tags/"
fun Const.ApiUrl.Comments() = this.url + "comments/"
fun Const.ApiUrl.Articles() = this.url + "articles/"
fun Const.ApiUrl.Groups() = this.url + "groups/"
fun Const.ApiUrl.Users() = this.url + "users/"
fun Const.ApiUrl.Specified(id: Int) = this.url + "$id/"
